---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Start Elasticsearch.
  service: name=elasticsearch state=started enabled=yes
