- name : Configure webserver with nginx
  hosts : webservers
  sudo : True
  tasks :
    
    - name : install nginx
      apt : name=nginx

    - name : copy nginx config file
      copy : src=../files/nginx.conf dest=/etc/nginx/

    - name : copy index.html
      template : >
        src=../templates/index.html.j2
        dest=/usr/share/nginx/html/index.html
        mode=0644
        notify : restart nginx

  handlers :
    - name : restart nginx
      service : name=nginx state=restarted
